version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    privileged: true
    restart: always
    ports:
      - '80:80'
    volumes:                                                            #nginx资料卷
      - './nginxdefault.conf:/etc/nginx/conf.d/default.conf'    #nginx配置文件
      - './dist:/usr/share/nginx/html'                               #html静态页面放这个文件夹
    command: /bin/bash -c "nginx -g 'daemon off;'"
